name: debttracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.3.beta

dependencies:
  flutter:
    sdk: flutter

  dart_mappable: ^4.6.1
  multiple_result: ^5.2.0
  riverpod_annotation: ^4.0.1
  http: ^1.6.0
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  decimal: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.2
  riverpod_generator: ^4.0.2
  build_runner: ^2.10.5
  dart_mappable_builder: ^4.6.3

flutter:
  uses-material-design: true
